version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: notes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U notes_user -d notes_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Бэкенд приложения
  be:
    image: protected-notes
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://protected-notes_user:secure_password@db:5432/protected-notes_db?schema=public"
      NODE_ENV: production
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.ImageName}}/{{.Name}}-{{.ID}}'
    ports:
      - "8080:8080"
    command: [ "npm", "run", "be:start" ]

  # Фронтенд приложения
  fe:
    image: protected-notes
    restart: always
    depends_on:
      be:
        condition: service_started
    environment:
      NEXT_PUBLIC_API_URL: "http://be:8080"
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        tag: '{{.ImageName}}/{{.Name}}-{{.ID}}'
    ports:
      - "3000:3000"
    command: [ "node", "./fe/.next/standalone/fe/server.js" ]

volumes:
  postgres_data:
